from typing import Any, Callable

from langchain_core.callbacks import BaseCallbackHandler


class StreamHandler(BaseCallbackHandler):
    """Handler for streaming LLM tokens in real-time."""

    def __init__(self, on_token: Callable[[str], None]) -> None:
        self.on_token = on_token

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """Called when a new token is generated by the LLM."""
        self.on_token(token)
