from langchain_core.callbacks import BaseCallbackHandler

class StreamHandler(BaseCallbackHandler):
    """Handler for streaming LLM tokens in real-time."""
    def __init__(self, on_token):
        self.on_token = on_token

    def on_llm_new_token(self, token, **kwargs):
        """Called when a new token is generated by the LLM."""
        self.on_token(token)